Upgrade to Angular 11
rsaenen/ngx-custom-validators pull request #48
Opened 2020-11-15 17:44 UTC by marko164

`ng test` and `ng lint` both pass

I removed dependecy to `@angular/router` since `DevModule` has only one component. If this changes in the future, I think `@angular/router` should be added to dev dependencies.

2020-11-16 06:19 UTC, liwonder commented
@rsaenen @marko164 Can we use the 'peerDependency' instead of 'dependency'?

2020-11-16 22:12 UTC, marko164 commented
I think peer dependency would require parent project to have it. And not every angular project must depend on @angular/router

2020-11-24 09:31 UTC, rsaenen requested changes

2020-11-24 09:31 UTC, rsaenen commented on package.json
> +    "@angular/common": "~11.0.0",
Could you migrate core/common/forms to peerDependencies ?

2020-11-24 09:32 UTC, rsaenen commented
Thanks a lot to keep this package up!

2020-11-29 11:14 UTC, smnbbrv commented
@rsaenen why does the lib get broken with every angular update? Can this issue be properly handled that it's not failing with next versions?

2020-12-10 13:18 UTC, rsaenen commented
@smnbbrv This package has basic functions and follows guidelines.
I think build isn't retrocompatible with each Angular major releases, afaik this package needs `ng update` and keep `ng-packagr` updated

2020-12-10 13:45 UTC, merged

2020-12-10 13:49 UTC, rsaenen commented
Released with 11.0.0